=== hajimen/flowerflower/ff_compile/schema/flowerflower.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://kaoriha.org/flowerflower/20130216/" targetNamespace="http://kaoriha.org/flowerflower/20130216/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:group ref="rootGroup"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:group name="rootGroup">
		<xs:choice>
			<xs:element ref="text"/>
			<xs:element ref="chapter"/>
			<xs:element ref="section"/>
			<xs:element ref="footnote"/>
			<xs:element ref="separation"/>
			<xs:element ref="characterNote"/>
			<xs:element ref="div"/>
			<xs:element ref="raw"/>
		</xs:choice>
	</xs:group>

	<xs:group name="pGroup">
		<xs:choice>
			<xs:element ref="ruby"/>
			<xs:element ref="span"/>
			<xs:element ref="raw"/>
		</xs:choice>
	</xs:group>

	<xs:element name="text">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="pGroup"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="ruby">
		<xs:complexType mixed="true">
			<xs:attribute name="text" type="xs:normalizedString" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="div">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="rootGroup"/>
			</xs:choice>
			<xs:attribute name="class" type="xs:normalizedString" use="optional"/>
			<xs:attribute name="style" type="xs:normalizedString" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="span">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="pGroup"/>
			</xs:choice>
			<xs:attribute name="class" type="xs:normalizedString" use="optional"/>
			<xs:attribute name="style" type="xs:normalizedString" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="raw">
		<xs:complexType mixed="true">
		</xs:complexType>
	</xs:element>

	<xs:complexType name="separationId">
	</xs:complexType>

	<xs:element name="chapter">
		<xs:complexType>
			<xs:attribute name="name" type="xs:normalizedString" use="required"/>
			<xs:attribute name="separationId" type="xs:normalizedString"/>
			<xs:attribute name="pushMessage" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="section">
		<xs:complexType />
	</xs:element>

	<xs:element name="footnote">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="pGroup"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="separation">
		<xs:complexType>
			<xs:attribute name="id" type="xs:normalizedString"/>
			<xs:attribute name="pushMessage" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="characterNote">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="text"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:normalizedString" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== hajimen/flowerflower/ff_compile/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root xmlns="http://kaoriha.org/flowerflower/20130216/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://kaoriha.org/flowerflower/20130216/ schema/flowerflower.xsd">
    <chapter pushMessage="紅茶ボタン 第1回が配信されました。" separationId="04c05eb9-ca71-4716-b3ca-5695d1a2a2ed" name="第1章 C'est la vie"/>
    <text>
　話を始めたいのだけれど、いつのどこから<ruby>始<rt>はじ</rt></ruby>めたらいいのかと考え始めると、私の頭はこんがらがってしまう。
　たとえば、ヴィノフラディの酒場の店主ランパじいさんは、客にツケを請求して払ってもらえなかったとき、よくこんなことを言ったらしい。「人間にはときどき金つんぼになる瞬間が訪れるものだ」。金がない、払いたくない、人違いだ、覚えがない、などなどの返事がくればそれは幸運にもちゃんと話が通じたケースで、お前の口の利きかたが気に食わない、ツケという仕組みが間違っている、酒代なんてもともとあってないようなものなんだからツケもあってないようなもの、売上が発生すればそれだけ酒税を取られるんだからお前だっていい気はしないだろう、てなあたりもまだマシなほうで、あなたは神を信じますか、うちのガキが生意気でよお、マツコデラックスってすごくない？　くらいが期待値で、本当に金つんぼになって返事をしない客も多いんだろう、なんてことを私はこの話から想像する。
　でも私はヴィノフラディがどんなところか知らない。ランパじいさんが何者か知らない。もしかするとランパじいさんは客の個人識別やツケの管理に関心がなくて、無関係な客に手当たり次第にありもしないツケを請求していたのかもしれない。ヴィノフラディはそんなデタラメがまかりとおる無法の巷だったのかもしれない。もしそうだとするとランパじいさんの話は、私が想像したのとは全然違って、金つんぼなのはランパじいさんのほう、という話になってしまう。
　ランパじいさんの話をするには、ヴィノフラディがどんなところで、ランパじいさんが何者なのか、という話をしないといけない。でないと結局なんの話をしているのかわからない。私はそれを知らずにランパじいさんの話をしているのだから、つまりなんの話をしているかというと、要するに、これが人生だ。セ・ラ・ヴィー。
　さて私は二〇一一年十二月一五日午後三時すぎ、私立渋谷星栄学園のマイコン部の部室前に立った。マイコン部の部室は旧校舎にあって、暖房はスチームだから節電のご時世でもそんなに寒くない。そろそろ、なんの話だかわからなくなってきた。今年は震災のせいで電力不足になったせいで節電のためエアコンを自粛したせいで、暑かったり寒かったりした。三つも「せいで」が重なったうえに「のため」までつくのだから、きっと風が吹けば桶屋が儲かる。スチームは、重油を燃やして水を沸かして高温の蒸気を作り、この蒸気を建物のなかのパイプに通して熱を運ぶ仕組み、らしい。確かめたわけじゃないから騙されているかもしれない。私がこの目で見て耳で聞いて肌で感じたのは、教室の窓際にオイルヒーターっぽいものが備え付けてあり、それが冬になると熱くなってカンカン鳴る、ということ。なぜ鳴るのかは知らない。もしかすると世界創成の秘密が隠されているかもしれない。リンゴが落ちても万有引力の法則で、箸が転がってもおかしい。
　「なにかご用？」
　振り向くと、これが人生だ。
</text>
    <characterNote name="後藤青">
    <text>　私。</text>
    </characterNote>
    <separation pushMessage="紅茶ボタン 第2回が配信されました。" id="fcf000e5-15f7-42e2-8509-d5a0e1102a0b"/>
    <text>

			＊

　一年のとき囲碁部で一緒で今でもわりと仲良くしている有吉さんが言うことには、アメリカの大統領はメガネをかけない。ポルポトは正しかったんだよ、と有吉さんは言わなかった。ポルポトという人は昔のどこかの独裁者で、メガネの人を皆殺しにしたらしい。きっとメガネの人が嫌いだったんだろう。今のアメリカ人もきっとメガネの人が嫌いで、そこはポルポトと同じだけれど、共通点があるというだけで別にどちらも正しいわけじゃないから、ポルポトは正しかったんだよ、と有吉さんは言わなかった。そもそも有吉さんはポルポトなんて知らなかったのでは、という疑惑は永久に藪のなかだ。
</text>
    <characterNote name="有吉さん">
	<text>　一年のとき囲碁部で一緒だった人。今でもわりと仲がいい。せこいことが大好き。</text>
	</characterNote>
    <text>
　アメリカの大統領はメガネをかけないらしい。そして私が言うことには、アメリカの大統領には妻がいる。でも『アメリカン・プレジデント』という映画のなかには、やもめの大統領がいて、女とデートに行ったりする。この大統領には親切で気のきく娘がいて、デートに出かける父親に向かって「相手の靴を褒めなさい」とアドバイスする。お世辞を言うときに難しいのは、褒めるところの選択で、たとえば相手がいくら美人でも、顔を褒めると空気が重たい。美人かどうかは女の人生にずっしりのしかかる重たい問題で、シャレにならない。靴なら簡単に取り替えられるから重たくないし、それでいて、こだわる人だと靴に人生をかける。でも、そこまで靴にこだわる人の靴を褒めるのは危ないかもしれない。下手な靴を褒めたら殺されるかもしれない。靴にこだわるといっても、昔のフィリピンの大統領夫人みたいに何千足も持っている人は、何千足のなかにはどうしたってあるはずのハズレの何十足が許せるのだから、下手な靴を褒めてもきっと許してもらえる。四足くらいの人が危ない。その四足は、世界中の何百万もの靴のなかから選び抜かれた世界ランキング一位から四位までの四足で、靴として許せるのはせいぜい世界ランキング十万位くらいまでかもしれない。デートに行く途中に、踏切のレールの溝に靴がはまって取れなくなり、取るのをあきらめて近くの店に駆け込んで、世界ランキング百五十万位あたりの靴を見繕って履いていったのに、デートの相手がよりによってその靴を褒めたりしたら、殺人事件が始まる。親切で気のきく人のアドバイスを真に受けると、こういう悲劇が起こる。
　「なにかご用？」
　振り向いて、これが人生で、そして相手の足元を見た。学校の制服で決まっているとおりの茶色いローファーだった。一目見て、この靴を褒めるのはよしたほうがいいと思った。どう見てもただの履き古した靴で、褒めるには、私の知らない物の見方が要る。別にどうってことのない茶碗が国宝だったりするように、この靴も、その筋の人が見れば国宝なのかもしれない。靴の甲についたシワにわびさびがあるとか、かかとのほつれが絶妙だとか、靴底の減りかたが見事に左右対称だとか。これまた一年のとき囲碁部で一緒だった有吉さんが言うことには、体つきが左右対称な人は魅力的に見えるらしく、だからできるだけ左右対称を保つために、奇数の日はカバンを右手で、偶数の日は左手で持つ、と有吉さんは言っていた。体つきが左右対称なら靴底の減りかたも左右対称になりやすいはずで、とするとそういう靴は、履いている人の魅力を表すかもしれない。だからといって靴底にやすりをかけて左右対称にしても、履いている人の魅力が高まったりはしない。これについては小学六年の秋に一瞬だけ仲良くしていた高浜さんが吐いたあの一言を引き合いに出したい。学校の昼休みに仲間で集まって、ファッション誌に載っていた面白いベルトをあれこれと品評していたら、誰かが「でもこれ二万円」と指摘し、追い討ちをかけるように高浜さんが「こういうの真似してさ、××ちゃんみたい～って言われたい？」と言ったのだった。
</text>
    <separation pushMessage="紅茶ボタン 第3回が配信されました。" id="430522c0-0eeb-4920-9cca-7b69302c2fa4"/>
    <text>
　ここまでの話では、まるで私が彼女の靴底を目撃したかのように聞こえるかもしれないので、念のため断っておくと、見なかった。靴底の減りかたが見事に左右対称というのは、私が思いついただけのことで、私は彼女の靴底を見なかった。とはいえ私の思いつきが当たっていてもおかしくはない。彼女の立っている姿は見事に左右対称だった。カバンの取っ手を両手で持っていたのも左右対称に一役買っていた。左右の肩の高さは測って合わせたように同じだった。
　靴底は見なかったけれど、靴の甲はちゃんと見たし、履き古しだったことも間違いない。その日のほんの数日前、同じクラスの国村さんと、どうして上級生の靴はよれよれなんだろう、という話をしたばかりだった。国村さんにはお姉さんがいたので、その答えを知っていた。子供のうちは成長につれて足が大きくなるので、靴がよれよれになる前にサイズが合わなくなって、新しいのに買い替える。大人の足は大きくならないので、古くなった靴にどこかで見切りをつけて買い替える。成長が止まったばかりの上級生は、古くなった靴に見切りをつけることをまだ知らないので、よれよれになっても履きつづける、と国村さんは言った。私はこの会話のことを思い出しながら彼女の靴を眺めて、上級生なんだ、と思った。自分の成長が止まったことは身体測定で数字を見て知っているはずなのに、古くなった靴に見切りをつけて買い替えることはまだ知らない、そういう上級生だと思った。
　「入部希望です」
　「じゃ、入って」
　彼女はメガネをかけていなかった。アメリカの大統領になれるかもしれない。
　と一瞬思ったものの、妻のほうはどうなのかと思い直した。彼女の場合、メガネをコンタクトにするよりも、妻を見繕うほうがきっと難しい。と一瞬思ったものの、かけてもいないメガネをコンタクトにするのは不可能なので、やっぱり妻を見繕うほうが簡単だ。と一瞬思ったものの、メガネをかけていないのならかければいいのだから、やっぱり妻を見繕うほうが難しい。と一瞬思ったものの、彼女に妻がいないと決めつけるのは偏見だ。法律上の妻でなくても内縁の妻や許婚がいるかもしれない。と一瞬思ったものの、彼女の横顔を見ると、やっぱりそんなファンタジーな話はなさそうだと思った。
　「ん？」
　「いえ」
　私は視線をそらした。
　そんなファンタジーな話はなくても、もっと別のファンタジーな話はあるかもしれない、と思った。
</text>
    <separation pushMessage="紅茶ボタン 第4回が配信されました。" id="1a9f9b5d-57b1-4854-871e-465e7e198f6c"/>
    <text>

			＊

　大事なことは何度も繰り返して言わなければならない。たとえば、デメントという学者は講義のとき、大事なことをこんな風に繰り返し言って聞かせたらしい。「英国の平均的な生徒たちは、ヘイスティングスの戦いは一〇六六年、ということのほかに、歴史についてはほとんど何も覚えていない。もし子供が何かほかのことを覚えているとしたら、それは一〇六六年の日付だというのだ。しかし私の講義では、重要なメッセージはほんのわずかしかない。たとえば――」。こうやってデメントは学生たちに訴えた、ほかのことはすべて忘れても、ほんのわずかの重要なメッセージだけは覚えてほしい、と。デメントが出した期末試験の最後の問題は、「講義のなかで、あなたが生涯忘れないと思ったことを一つだけ書きなさい」。ほとんどすべての学生が、「一〇六六年」と答えたという。大事なことを何度も繰り返して言うことの効用がよくわかる。
　私のこの話にも、重要なメッセージはほんのわずかしかない。たとえば――
　「寒い？」
　彼女は窓際にあるオイルヒーター風のなにかを操作した。オイルヒーター風のなにか、というのはスチームといえばスチームなのだけれど、スチームは建物全体のシステムのことじゃないかと思う。だとするとこのオイルヒーター風のなにかを指してスチームと呼ぶのは、自動車のハンドルを指して自動車と呼ぶような変な話になってしまう。こういう変な話といえば、ホテルのエアコンの話をまんがで読んだことがある。そのホテルの冷房は、ひとつの大きなエアコンから吹き出す冷気をたくさんの客室に分配する仕組みで、客室にあるエアコンのコントローラーは冷気の開け閉めと風の強さを変えるだけのもので、つまり客室ごとにエアコンがついているのではなく、だから客室にあるエアコンのコントローラーがコントロールしているのは元締めの大きなエアコンではない。ならなんのコントローラーと呼べばいいのかと思うところなのに、まんがはその話はすっ飛ばして、家にあるエアコンと同じようなつもりでその謎のコントローラーを操作してもうまくいかない、という話になったので、変な話だと思った。とはいえ、冷気を吹き出すあの白い機械がエアコンなのかと改めて考えてみると、よくわからない。室外機と白い機械とリモコンの三位一体のシステムがエアコンなのかもしれない。だとするとホテルの客室にある謎のコントローラーも立派にエアコンのコントローラーということになる。こんな具合に、変な話はどこまでも変な話になってしまう。窓際にあるオイルヒーター風のなにかは、こういう変な話に火をつける危険物なので、これからはできるだけ避けて通る。
　「いいえ」
　「マイコン、好き？」
　私は彼女の質問をシリーズ化してみた。『二次方程式の解の公式、好き？』『炭化水素、好き？』『モホロビチッチ不連続面、好き？』『細胞膜、好き？』『振り子の等時性、好き？』。私はこのなかではモホロビチッチ不連続面が好きです。数学の定理に人の名前がついているのは、少しでも数学を好きになってもらうための涙ぐましい努力なんだろうと思う。でも、モホロビチッチと比べると地味でつまらない名前ばかりで、十把一絡げのゆるキャラ大集合みたいな雰囲気が漂っている。これから数学者になる人はネーミングの専門家に相談して、モホロビチッチみたいなペンネームをつけたらいいと思う。そんなわけで、さっきのシリーズで私はわざと元素の名前を使わなかった。元素にはいい名前がたくさんあって、たとえば『テルル、好き？』なんてそんなの好きに決まっているからつまらない。じゃあモホロビチッチ不連続面なんて明らかに地学をひいきしてるだろ、というツッコミを私は彼女の質問もろともスルーした。
　「私、後藤青といいます」
　「佐野時子です。よろしくね」
　「よろしくお願いします」
</text>
    <characterNote name="佐野時子">
    <text>　マイコン部を訪れて最初に出会った人。立ち姿が左右対称。</text>
    </characterNote>
    <separation pushMessage="紅茶ボタン 第5回が配信されました。" id="21e28c75-a001-48ef-bf34-7f30ad998107"/>
    <text>
　彼女は窓のカーテンを引いた。すると、窓の下のほうを一部ふさいでダーツボードが置いてあり、それを見た私は、数字とピタゴラスとピタゴラ装置の三者をめぐる問題を思い浮かべないわけにはいかなかった。そのダーツボードは電気仕掛けで採点するタイプで、右下に点数を出す液晶画面がついている。ダーツは的の形だけ見ると、アーチェリーや射撃のように真ん中に当てればハイスコアなのかと思うけれど、実はトランプのように、先に数字の組み合わせを完成させた人が勝つ。だからダーツの点数は、一番少ないのが零点で一番大きいのが世界記録の大きければ大きいほどいい数字ではなく、サイコロの目やトランプの数字のように、ひとつひとつが別々の意味を持っている。数字のひとつひとつに意味があるといえば、ピタゴラスを思い出さないわけにはいかない。一は理性、二は女、三は男、四は正義と真理、五は結婚、六は恋愛と霊魂、七は幸福、八は愛、十は神聖な数、という具合にピタゴラスは数字のひとつひとつに意味を見出した、と数学の授業で先生が言っていた。うちのクラスの占いマニアの庄司さんが言うことには、トランプはタロットからできたもので、タロットの数字札の数字にはそれぞれ意味があるらしい。タロットからトランプ、ダーツへと、ピタゴラスな数字の仲間は続いている。ここで気になるのは、ピタゴラスイッチのピタゴラ装置はなにがどうピタゴラスなのかという疑問で、私はそれを解く手がかりをこのダーツボードに発見した。というのも、電気仕掛けで採点するこのダーツボードはピタゴラスな数字を扱う装置だから、と一瞬思ったけれど、ピタゴラ装置のどこにも数字は出てこないと気づいた。
　「適当に座ってて」
　彼女はロッカーを開けて、コートやカバンをしまい、本を出した。私はそのときどちらかといえば窓の近くに立っていて、初めて彼女を少し遠くから眺めた。
　一は理性、二は女、三は男、そして五十八は若い女性芸能人のウェストだ。この例を見てもわかるとおり、ピタゴラスは当たらずとも遠からずのいい線を行っていた。五十八の五は結婚、つまり「あの人と結婚できたらいいな」というファンの願望をかきたてる五で、五十八の十は神聖な数、つまりファンが芸能人を神聖視する十で、五十八の八は愛、つまりファンが芸能人を愛する八、というわけだ。彼女はたぶん芸能人ではないと思うけれど、ウェストは五十八がふさわしい。芸能人のウェスト以外のスリーサイズや体重がけっこうばらついているのは、芸能人のキャラがいろいろあるからだ。モデルなら体重は三十八か四十八、グラビアアイドルなら四十二か五十二がふさわしい。というのも、二は女だからグラビアアイドルの売りにぴったりだし、三は男なのでグラビアアイドルのファンには要らないし、逆に五の結婚はモデルのファンには要らない。彼女の体重は、四十八と五十二のどちらがふさわしいかと私はちょっと迷い、結局、五十二にしておいた。体型的にはそっちだし、四の正義と真理よりも五の結婚のほうがいい。
　「あの、入部のことですけど」
　「部長が来るまで待ってて」
</text>
    <separation pushMessage="紅茶ボタン 第6回が配信されました。" id="f06fc7be-0f68-4d24-a301-aa3b03239cef"/>
    <text>
　彼女は椅子に座って本を開いた。部室の奥行きは普通の教室と同じなのに幅が恐ろしく狭くて、左右に手を広げると指先が壁につくくらいだった。そこに長机を置いてあるから、普通に長机の長辺に向かって座ると、人の通り道がなくなってしまう。彼女は長机の短辺に向かって座り、私はそれを見て、彼女の正面にあたる短辺に向かって座ったら、この配置はよくない、とすぐに思った。
　話は私が一年のとき囲碁部に入ったところにまでさかのぼる。囲碁部のオリエンテーションで私は有吉さんの隣に座り、それで有吉さんと仲良くなり、それで私も囲碁部なのに将棋を指すことになり、ひいては囲碁部も将棋もやめることになった。というのも有吉さんは、囲碁部が将棋も守備範囲と聞いて入部したものの、有吉さん以外に誰も指さないので、私がつきあって指すことになり、すると私と有吉さんは部のなかで浮いて、このまま居続けてもしょうがないと思ってやめたら、そもそも私が将棋を指したのは部で有吉さんにつきあってのことだから指さなくなったのだった。ちなみに有吉さんは今では携帯の通信対戦で楽しくやっているらしい。この話だけでも配置は大切だとわかるけれど、将棋にとって配置はさらに重要で、なにしろ将棋には駒の配置のほかには手番しかない。手番、つまり相手と自分のどちらが次に指す番か、なんて馬鹿馬鹿しいくらいわかりきっている、と思うのは長考したことのない人の浅はかさで、三十秒も考えたら頭がこんがらがって「あれっ、実は向こうの手番？」と思えてくるし、そうすると相手も「実は私の手番？」と疑い出し、そうなると知らん顔して指してしまいたくなるのだけれど、もし相手が自分の手番だと確信していると、それは二手指しだと言われてしまい、お互いに自分の手番と言い張るはめになり、それでどちらも折れなければその勝負はそこで打ち切りになってしまってお互いに嫌な思いだけが残るから、相手が指したときに今は自分の手番じゃないかと思ってもなかなか言い出せない。長考とはこういう心理戦なのだ。ちなみに、王手をかけられて初めて長考する人がいるのは、どちらの手番かわからなくなる恐れがなくて安心して長考できるからだ。有吉さんはこういう機微に詳しくて、たとえば左右中央の下から二段目に歩があるときは二歩を見落としやすいから、そのときは二歩を打たせるように仕向けるといいらしい。歩があるのが一番下の段だとめったにひっかからないらしいので、これもまた配置のなせる妙だ。局面が悪くて勝ち目がないと思ったら、まず盤上に二歩がないかどうかをチェックするといい。もし相手が二歩していれば、その場で勝ちになる。二歩が見つからない場合には、互いの持ち駒と盤上の駒を数えて、金銀桂香がそれぞれ四枚あるかどうか、歩が十八枚ぴったりあるかどうかをチェックし、もし数が足りなければ駒がどこかに落ちているので探して拾って自分の持ち駒に加え、もし余分な駒があればクレームをつけて勝負を打ち切り、もし数がルールどおりなら、前もって隣の盤から抜いて隠しておいた銀をこっそり自分の持ち駒に加えろ、と有吉さんは言っていた。こういう戦法を教わるたびに、だから有吉さんは弱いんだ、と私は納得した。
　そういうわけで、長机の長辺を挟んで彼女の正面真向かいに座る、という配置はよくないので、私はすぐに席を立って、部室のなかを家捜ししはじめた。すぐに目についたのは、出入口のドアにかけてあるダーツボードで、窓をふさいでいるのと同じく電気仕掛けで採点するタイプだった。
　「ダーツ、流行ってるんですか？」
</text>
    <separation pushMessage="紅茶ボタン 第7回が配信されました。" id="4bbd08bb-f1f0-4e80-8d45-82756ebd89b8"/>
    <text>
　窓とドアのダーツボードをそれぞれ両手で指差すと、彼女はまるで知らない外国語で話し掛けられでもしたかのように、あいまいな表情で何度かまばたきをしてから、こう問い返した。
　「文化祭で見たことない？」
　「ありません」
　「そう」
　彼女は本のページに視線を戻した。
　「あの、いけなかったですか」
　「そういうのがいけないんだったら、嫌だな」
　「どっちなんですか」
　「それは部長が決めること」
　彼女は本から目を離さない。私は家捜しを再開した。
